
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 05 22:42:33 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Tiempo = 7;
  public static final int Longitud = 5;
  public static final int Menor = 9;
  public static final int Velocidad = 8;
  public static final int ERROR = 16;
  public static final int Letra = 12;
  public static final int EOF = 0;
  public static final int SignoIgual = 6;
  public static final int Latitud = 4;
  public static final int Fecha = 13;
  public static final int Inicio = 2;
  public static final int error = 1;
  public static final int Guion = 15;
  public static final int Mayor = 10;
  public static final int Horasegmin = 14;
  public static final int Numero = 11;
  public static final int Final = 3;
}

